-- articles table; TZ with timezone (UTC)
CREATE TABLE blogful_articles (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
  title TEXT NOT NULL,
  date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
  content TEXT
);
